# Generated by Django 4.1.7 on 2023-03-03 16:47

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=100, verbose_name='Edifício')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Locatario')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Nº Apto')),
                ('quartos', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nº de quartos')),
                ('banheiros', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nº de quartos')),
                ('vagas', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nº de vagas')),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='m²')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('imagem1', stdimage.models.StdImageField(force_min_size=False, upload_to='media/apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 1')),
                ('imagem2', stdimage.models.StdImageField(force_min_size=False, upload_to='media/apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 2')),
                ('imagem3', stdimage.models.StdImageField(force_min_size=False, upload_to='media/apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 3')),
                ('imagem4', stdimage.models.StdImageField(force_min_size=False, upload_to='media/apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 4')),
                ('imagem5', stdimage.models.StdImageField(force_min_size=False, upload_to='media/apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 5')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponivel?')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.building')),
                ('locatario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client')),
            ],
        ),
    ]
