# Generated by Django 4.1.7 on 2023-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartament',
            name='banheiros',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nº de banheiros'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
