# Generated by Django 4.1.7 on 2023-03-03 23:46

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Nº Apto')),
                ('quartos', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nº de quartos')),
                ('banheiros', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nº de banheiros')),
                ('vagas', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nº de vagas')),
                ('tamanho', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='m²')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='cod. identificação')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Valor')),
                ('imagem1', stdimage.models.StdImageField(force_min_size=False, upload_to='apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 1')),
                ('imagem2', stdimage.models.StdImageField(force_min_size=False, upload_to='apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 2')),
                ('imagem3', stdimage.models.StdImageField(force_min_size=False, upload_to='apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 3')),
                ('imagem4', stdimage.models.StdImageField(force_min_size=False, upload_to='apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 4')),
                ('imagem5', stdimage.models.StdImageField(force_min_size=False, upload_to='apartamentos', variations={'thump': {'crop': True, 'height': 367, 'width': 457}}, verbose_name='Imagem 5')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponivel?')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatario', models.CharField(max_length=100, verbose_name='Locatario')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.RenameModel(
            old_name='Building',
            new_name='Edificio',
        ),
        migrations.DeleteModel(
            name='Apartament',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.edificio'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='locatario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
    ]
