# Generated by Django 4.1.7 on 2023-03-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apartament_banheiros_alter_client_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartament',
            name='apartamento',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Nº Apto'),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='banheiros',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nº de banheiros'),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='quartos',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nº de quartos'),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='tamanho',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='m²'),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='vagas',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nº de vagas'),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Valor'),
        ),
    ]
