# Generated by Django 4.1.7 on 2023-03-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apartamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='locatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
    ]
